// Edexcel IAL & CIE exam-technique FAQs — researched from official mark schemes.
// Each entry: question, mark-scheme answer, examiner note.

import type { SubjectCode } from "./subjects";

export type Board = "edexcel-ial" | "cie";

export interface ExamFaq {
  id: string;
  board: Board;
  subject: SubjectCode;
  topic: string;
  question: string;
  answer: string;
  examiner_note: string;
}

const ED = "edexcel-ial" as const;
const CIE = "cie" as const;

export const EXAM_FAQS: ExamFaq[] = [
  // ===== EDEXCEL IAL CHEMISTRY (15) =====
  { id: "ec1", board: ED, subject: "chemistry", topic: "Kinetics", question: "Define rate of reaction.", answer: "The change in concentration of a reactant or product per unit time. Units: mol dm⁻³ s⁻¹.", examiner_note: "Use 'rate', not 'speed'. Always include units." },
  { id: "ec2", board: ED, subject: "chemistry", topic: "Kinetics", question: "Define activation energy.", answer: "The minimum energy required for colliding particles to react.", examiner_note: "'Minimum' is a required mark-scheme word — omitting it loses the mark." },
  { id: "ec3", board: ED, subject: "chemistry", topic: "Acid-base Equilibria", question: "Define pH.", answer: "pH = −log₁₀[H⁺] where [H⁺] is the concentration of hydrogen ions in mol dm⁻³.", examiner_note: "Must reference H⁺ concentration explicitly, not just 'acidity'." },
  { id: "ec4", board: ED, subject: "chemistry", topic: "Acid-base Equilibria", question: "What is a buffer solution?", answer: "A solution that resists changes in pH when small amounts of acid or alkali are added.", examiner_note: "'Resists changes' — not 'maintains constant pH'. The distinction matters." },
  { id: "ec5", board: ED, subject: "chemistry", topic: "Electrochemistry", question: "Define standard electrode potential.", answer: "The EMF of a half-cell connected to a standard hydrogen electrode under standard conditions (298 K, 100 kPa, 1.00 mol dm⁻³ solutions).", examiner_note: "All three standard conditions must be referenced for full marks." },
  { id: "ec6", board: ED, subject: "chemistry", topic: "Bonding and Structure", question: "Define electronegativity.", answer: "The ability of an atom to attract a bonding pair of electrons in a covalent bond.", examiner_note: "Must say 'bonding pair' — not just 'electrons'." },
  { id: "ec7", board: ED, subject: "chemistry", topic: "Atomic Structure", question: "Define first ionisation energy.", answer: "The energy required to remove one mole of electrons from one mole of gaseous atoms to form one mole of gaseous 1+ ions.", examiner_note: "All three 'gaseous' state symbols and 'one mole' references are required." },
  { id: "ec8", board: ED, subject: "chemistry", topic: "Energetics", question: "Define standard enthalpy of formation.", answer: "The enthalpy change when one mole of a compound is formed from its elements in their standard states under standard conditions (100 kPa, 298 K).", examiner_note: "'One mole' and 'standard states' both required." },
  { id: "ec9", board: ED, subject: "chemistry", topic: "Energetics", question: "State Hess's Law.", answer: "The total enthalpy change for a reaction is independent of the route taken, provided the initial and final conditions are the same.", examiner_note: "'Independent of route' is the key phrase." },
  { id: "ec10", board: ED, subject: "chemistry", topic: "Chemical Equilibria", question: "State Le Chatelier's principle.", answer: "When a system at equilibrium is disturbed, the position of equilibrium shifts to counteract the change.", examiner_note: "Don't say 'reverses the change' — say 'counteracts'." },
  { id: "ec11", board: ED, subject: "chemistry", topic: "Kinetics", question: "What is a catalyst?", answer: "A substance that increases the rate of reaction by providing an alternative reaction pathway with a lower activation energy, without being used up.", examiner_note: "Include 'alternative pathway', 'lower activation energy', and 'not used up' — three marking points." },
  { id: "ec12", board: ED, subject: "chemistry", topic: "Transition Metals", question: "Define a transition element.", answer: "A d-block element that forms at least one stable ion with a partially filled d-subshell.", examiner_note: "'Partially filled d-subshell' is the discriminator from Sc and Zn." },
  { id: "ec13", board: ED, subject: "chemistry", topic: "Entropy and Energetics", question: "Define entropy.", answer: "A measure of the disorder of a system; the number of ways energy and particles can be arranged.", examiner_note: "Either definition accepted. Don't write only 'randomness'." },
  { id: "ec14", board: ED, subject: "chemistry", topic: "Bonding", question: "Why does diamond have a very high melting point?", answer: "Diamond has a giant covalent (macromolecular) structure with strong covalent bonds between carbon atoms; a large amount of energy is required to break these bonds.", examiner_note: "Must specify 'covalent' bonds — students often write 'intermolecular forces' here, which is wrong." },
  { id: "ec15", board: ED, subject: "chemistry", topic: "Organic Chemistry", question: "Define an electrophile.", answer: "An electron-pair acceptor.", examiner_note: "Don't say 'positive ion' — many electrophiles are neutral (e.g. SO₃)." },

  // ===== EDEXCEL IAL BIOLOGY (15) =====
  { id: "eb1", board: ED, subject: "biology", topic: "Genes and Health", question: "Define a gene.", answer: "A sequence of DNA bases that codes for a specific polypeptide / protein.", examiner_note: "Polypeptide is preferred over protein for full marks." },
  { id: "eb2", board: ED, subject: "biology", topic: "Genes and Health", question: "What is meant by the term allele?", answer: "A different version (form) of the same gene.", examiner_note: "Don't say 'a type of gene' — alleles are versions of the same gene." },
  { id: "eb3", board: ED, subject: "biology", topic: "Lifestyle and Health", question: "Describe the structure of an artery.", answer: "Thick muscular wall, narrow lumen, elastic fibres, smooth endothelium, no valves (except at the base of the aorta).", examiner_note: "Compare against vein answer — examiners look for the contrasting features." },
  { id: "eb4", board: ED, subject: "biology", topic: "Cell Structure", question: "Define a tissue.", answer: "A group of similar cells working together to perform a specific function.", examiner_note: "Don't confuse with 'organ' (different tissues working together)." },
  { id: "eb5", board: ED, subject: "biology", topic: "Voice of the Genome", question: "Define mitosis.", answer: "Nuclear division producing two genetically identical daughter cells with the same chromosome number as the parent cell.", examiner_note: "'Genetically identical' and 'same chromosome number' both required." },
  { id: "eb6", board: ED, subject: "biology", topic: "Voice of the Genome", question: "Define meiosis.", answer: "Nuclear division producing four genetically different haploid daughter cells from one diploid parent cell.", examiner_note: "Must include 'genetically different' AND 'haploid'." },
  { id: "eb7", board: ED, subject: "biology", topic: "Immunity", question: "Define an antigen.", answer: "A molecule (usually a protein) on the surface of a cell that triggers an immune response.", examiner_note: "'Triggers an immune response' is the marking point." },
  { id: "eb8", board: ED, subject: "biology", topic: "Immunity", question: "Describe the role of B-lymphocytes.", answer: "Recognise specific antigens; differentiate into plasma cells which secrete antibodies; some become memory cells for a faster secondary response.", examiner_note: "Three marking points: recognition, antibody production, memory." },
  { id: "eb9", board: ED, subject: "biology", topic: "Run for Your Life", question: "Compare slow and fast twitch muscle fibres.", answer: "Slow twitch: many mitochondria, lots of myoglobin (red), aerobic respiration, fatigue resistant. Fast twitch: few mitochondria, little myoglobin (white), anaerobic respiration, fatigue quickly.", examiner_note: "Compare in pairs — examiners want explicit contrast, not two separate descriptions." },
  { id: "eb10", board: ED, subject: "biology", topic: "Grey Matter", question: "Describe the structure of a synapse.", answer: "Pre-synaptic neurone, synaptic cleft, post-synaptic neurone with neurotransmitter receptors; vesicles in pre-synaptic knob containing neurotransmitter.", examiner_note: "Label diagram if asked — losing labelling marks is common." },
  { id: "eb11", board: ED, subject: "biology", topic: "Biodiversity", question: "Define biodiversity.", answer: "The variety of life in an ecosystem — measured at three levels: genetic diversity, species diversity, and ecosystem diversity.", examiner_note: "All three levels for 3-mark questions." },
  { id: "eb12", board: ED, subject: "biology", topic: "On the Wild Side", question: "Define a niche.", answer: "The role of an organism in its ecosystem — including its interactions with other organisms and its abiotic environment.", examiner_note: "Don't say just 'where it lives' — that's habitat." },
  { id: "eb13", board: ED, subject: "biology", topic: "Microbiology", question: "Define an antibiotic.", answer: "A chemical produced by a microorganism that kills (bactericidal) or inhibits the growth of (bacteriostatic) bacteria.", examiner_note: "Distinguish bactericidal vs bacteriostatic for full marks." },
  { id: "eb14", board: ED, subject: "biology", topic: "Genes and Health", question: "Describe protein synthesis.", answer: "Transcription: DNA unwinds, mRNA synthesised by RNA polymerase using DNA as template. Translation: mRNA binds to ribosome, tRNA brings amino acids matching codons, peptide bonds form.", examiner_note: "Examiners want clear separation of transcription and translation stages." },
  { id: "eb15", board: ED, subject: "biology", topic: "Lifestyle and Health", question: "Describe the cardiac cycle.", answer: "Atrial systole (atria contract, AV valves open, blood to ventricles); ventricular systole (ventricles contract, AV valves close, semilunar valves open, blood to arteries); diastole (all chambers relax, blood enters atria).", examiner_note: "Include valve states and pressure changes for full marks." },

  // ===== EDEXCEL IAL PHYSICS (15) =====
  { id: "ep1", board: ED, subject: "physics", topic: "Mechanics", question: "Define velocity.", answer: "The rate of change of displacement (a vector quantity), measured in m s⁻¹.", examiner_note: "Use 'displacement', not 'distance'. Vector vs scalar matters." },
  { id: "ep2", board: ED, subject: "physics", topic: "Mechanics", question: "State Newton's second law.", answer: "The resultant force on an object is proportional to the rate of change of its momentum (F = dp/dt). Equivalent: F = ma when mass is constant.", examiner_note: "Either form acceptable but state 'resultant force', not just 'force'." },
  { id: "ep3", board: ED, subject: "physics", topic: "Electric Circuits", question: "State Ohm's law.", answer: "The current through a metallic conductor at constant temperature is directly proportional to the potential difference across it.", examiner_note: "'At constant temperature' is required." },
  { id: "ep4", board: ED, subject: "physics", topic: "Electric Circuits", question: "Define electric current.", answer: "The rate of flow of electric charge: I = ΔQ/Δt, measured in amperes (A).", examiner_note: "'Rate of flow of charge' is the marking phrase." },
  { id: "ep5", board: ED, subject: "physics", topic: "Waves", question: "Define wavelength.", answer: "The distance between two adjacent points on a wave that are in phase. Unit: metres.", examiner_note: "'In phase' is the discriminator from generic 'one wave'." },
  { id: "ep6", board: ED, subject: "physics", topic: "Waves", question: "State the principle of superposition.", answer: "When two or more waves meet at a point, the resultant displacement is the vector sum of their individual displacements at that point.", examiner_note: "'Vector sum' or 'algebraic sum' both accepted." },
  { id: "ep7", board: ED, subject: "physics", topic: "Particle Nature of Light", question: "Define the photoelectric effect.", answer: "The emission of electrons from a metal surface when electromagnetic radiation of sufficiently high frequency is incident on it.", examiner_note: "Must reference 'frequency' (not just 'light') and 'sufficient'/'threshold' implied." },
  { id: "ep8", board: ED, subject: "physics", topic: "Further Mechanics", question: "Define simple harmonic motion.", answer: "Motion in which the acceleration is directly proportional to the displacement from equilibrium and is always directed towards the equilibrium position.", examiner_note: "Both conditions: proportionality AND direction towards equilibrium." },
  { id: "ep9", board: ED, subject: "physics", topic: "Electric Fields", question: "Define electric field strength.", answer: "The force per unit positive charge experienced by a small test charge placed at that point. E = F/Q. Unit: N C⁻¹ or V m⁻¹.", examiner_note: "'Per unit positive charge' — sign matters." },
  { id: "ep10", board: ED, subject: "physics", topic: "Magnetic Fields", question: "State Faraday's law.", answer: "The induced EMF is proportional to the rate of change of magnetic flux linkage.", examiner_note: "'Flux linkage' not just 'flux' for A2." },
  { id: "ep11", board: ED, subject: "physics", topic: "Magnetic Fields", question: "State Lenz's law.", answer: "The direction of any induced current is such that it opposes the change that produced it.", examiner_note: "'Opposes the change' — students often say 'opposes the motion' which is incomplete." },
  { id: "ep12", board: ED, subject: "physics", topic: "Nuclear Physics", question: "Define half-life.", answer: "The average time taken for half the radioactive nuclei in a sample to decay.", examiner_note: "'Average' is required because decay is random." },
  { id: "ep13", board: ED, subject: "physics", topic: "Thermodynamics", question: "Define specific heat capacity.", answer: "The energy required to raise the temperature of 1 kg of a substance by 1 K (or 1 °C). Unit: J kg⁻¹ K⁻¹.", examiner_note: "'1 kg' not 'unit mass' — be specific." },
  { id: "ep14", board: ED, subject: "physics", topic: "Oscillations", question: "Define damping.", answer: "The reduction in amplitude of an oscillation over time due to energy loss to the surroundings (e.g. friction, air resistance).", examiner_note: "Must include energy loss mechanism." },
  { id: "ep15", board: ED, subject: "physics", topic: "Cosmology", question: "State Hubble's law.", answer: "The recessional velocity of a galaxy is directly proportional to its distance from us: v = H₀d.", examiner_note: "Symbol H₀ is Hubble's constant; units are typically km s⁻¹ Mpc⁻¹." },

  // ===== EDEXCEL IAL MATHS (15) =====
  { id: "em1", board: ED, subject: "mathematics", topic: "Differentiation", question: "What does the derivative of a function represent?", answer: "The gradient of the tangent to the curve at a point; equivalently the instantaneous rate of change of y with respect to x.", examiner_note: "'Gradient of tangent' or 'rate of change' both award the mark." },
  { id: "em2", board: ED, subject: "mathematics", topic: "Integration", question: "What does the definite integral of f(x) from a to b represent?", answer: "The signed area between the curve y = f(x) and the x-axis between x = a and x = b.", examiner_note: "'Signed' — area below the axis counts as negative." },
  { id: "em3", board: ED, subject: "mathematics", topic: "Algebra", question: "When is a quadratic factorisable over the reals?", answer: "When the discriminant b² − 4ac ≥ 0 (≥ 0 for real roots, > 0 for distinct).", examiner_note: "Strict vs weak inequality matters for 'distinct' vs 'real'." },
  { id: "em4", board: ED, subject: "mathematics", topic: "Trigonometry", question: "State the small-angle approximation for sin x.", answer: "sin x ≈ x for small x in radians.", examiner_note: "'In radians' must be stated." },
  { id: "em5", board: ED, subject: "mathematics", topic: "Vectors", question: "When are two vectors perpendicular?", answer: "When their scalar (dot) product equals zero: a · b = 0.", examiner_note: "Show the dot product calculation explicitly." },
  { id: "em6", board: ED, subject: "mathematics", topic: "Vectors", question: "When are two vectors parallel?", answer: "When one is a scalar multiple of the other: a = λb for some real λ.", examiner_note: "State the value of λ to confirm parallelism in proofs." },
  { id: "em7", board: ED, subject: "mathematics", topic: "Sequences and Series", question: "State the formula for the sum of a geometric series.", answer: "Sₙ = a(1 − rⁿ)/(1 − r) for r ≠ 1. For |r| < 1, S∞ = a/(1 − r).", examiner_note: "State the convergence condition |r| < 1 when using S∞." },
  { id: "em8", board: ED, subject: "mathematics", topic: "Logarithms", question: "State the laws of logarithms.", answer: "log(ab) = log a + log b; log(a/b) = log a − log b; log(aⁿ) = n log a.", examiner_note: "Same base on both sides — examiners deduct for missing base." },
  { id: "em9", board: ED, subject: "mathematics", topic: "Differentiation", question: "When does a function have a stationary point?", answer: "When dy/dx = 0.", examiner_note: "Use second derivative test or sign change to classify max/min/inflection." },
  { id: "em10", board: ED, subject: "mathematics", topic: "Statistics", question: "State the conditions for a binomial distribution.", answer: "Fixed number of trials n; each trial has two outcomes (success/failure); constant probability of success p; trials are independent.", examiner_note: "All four conditions for full marks (often 4 marks)." },
  { id: "em11", board: ED, subject: "mathematics", topic: "Statistics", question: "What is meant by a Type I error?", answer: "Rejecting the null hypothesis when it is in fact true.", examiner_note: "Symmetric: Type II = accepting H₀ when it is false." },
  { id: "em12", board: ED, subject: "mathematics", topic: "Mechanics", question: "State the conditions for SUVAT to apply.", answer: "Constant acceleration in a straight line.", examiner_note: "Both conditions required — many students forget 'in a straight line'." },
  { id: "em13", board: ED, subject: "mathematics", topic: "Mechanics", question: "State Newton's third law.", answer: "If body A exerts a force on body B, then body B exerts an equal and opposite force on body A.", examiner_note: "Forces act on different bodies — common error to claim they cancel." },
  { id: "em14", board: ED, subject: "mathematics", topic: "Proof", question: "What is a proof by contradiction?", answer: "Assume the negation of the statement. Derive a logical contradiction. Conclude the original statement must be true.", examiner_note: "Three explicit steps required for the structure mark." },
  { id: "em15", board: ED, subject: "mathematics", topic: "Differential Equations", question: "What is meant by the general solution of a differential equation?", answer: "The family of all solutions, including the constant of integration; a particular solution is found by applying boundary/initial conditions.", examiner_note: "Always include +c until you apply conditions." },

  // ===== CIE CHEMISTRY 9701 (10) =====
  { id: "cc1", board: CIE, subject: "chemistry", topic: "Atomic Structure", question: "Define isotopes.", answer: "Atoms of the same element with the same number of protons but different numbers of neutrons.", examiner_note: "Must say 'same element' and reference both protons and neutrons." },
  { id: "cc2", board: CIE, subject: "chemistry", topic: "Atoms Molecules and Stoichiometry", question: "Define relative atomic mass.", answer: "The average mass of one atom of an element relative to 1/12 the mass of one atom of carbon-12.", examiner_note: "'1/12 of carbon-12' is required wording." },
  { id: "cc3", board: CIE, subject: "chemistry", topic: "Chemical Bonding", question: "Define a dative covalent (coordinate) bond.", answer: "A covalent bond in which both shared electrons are donated by one atom.", examiner_note: "'Both' electrons from 'one atom' — both phrases needed." },
  { id: "cc4", board: CIE, subject: "chemistry", topic: "Chemical Energetics", question: "State the first law of thermodynamics.", answer: "Energy can be neither created nor destroyed, only transferred from one form to another.", examiner_note: "'Transferred' is preferred over 'changed'." },
  { id: "cc5", board: CIE, subject: "chemistry", topic: "Equilibria", question: "State the equilibrium law (Kc expression).", answer: "For aA + bB ⇌ cC + dD: Kc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ at constant temperature.", examiner_note: "'At constant temperature' must be stated; Kc only changes with temperature." },
  { id: "cc6", board: CIE, subject: "chemistry", topic: "Reaction Kinetics", question: "Define order of reaction with respect to a reactant.", answer: "The power to which the concentration of that reactant is raised in the experimentally determined rate equation.", examiner_note: "'Experimentally determined' distinguishes from stoichiometric coefficients." },
  { id: "cc7", board: CIE, subject: "chemistry", topic: "Group 17", question: "Describe the trend in oxidising power down Group 17.", answer: "Oxidising power decreases down the group because atomic radius increases, so the attraction for an extra electron decreases.", examiner_note: "Always link the trend to atomic radius, NOT 'shielding alone'." },
  { id: "cc8", board: CIE, subject: "chemistry", topic: "Transition Elements", question: "Why are transition metal complexes coloured?", answer: "d-orbitals are split by ligands into different energy levels; an electron absorbs visible light to be promoted; the complementary colour is transmitted/seen.", examiner_note: "Three marking points: d-splitting, absorption, complementary colour." },
  { id: "cc9", board: CIE, subject: "chemistry", topic: "Hydrocarbons", question: "Describe the mechanism of free radical substitution of methane.", answer: "Initiation: Cl₂ → 2Cl· (UV). Propagation: Cl· + CH₄ → HCl + CH₃·; CH₃· + Cl₂ → CH₃Cl + Cl·. Termination: any two radicals combine.", examiner_note: "Three named stages required; show curly half-arrows for radicals." },
  { id: "cc10", board: CIE, subject: "chemistry", topic: "Analytical Techniques", question: "What does the molecular ion peak (M⁺) in mass spectrometry tell you?", answer: "The relative molecular mass of the compound.", examiner_note: "M⁺ peak is the highest m/z value (usually) corresponding to the parent molecule." },

  // ===== CIE BIOLOGY 9700 (10) =====
  { id: "cb1", board: CIE, subject: "biology", topic: "Cell Structure", question: "Define magnification and resolution.", answer: "Magnification: how many times larger an image is than the object. Resolution: the minimum distance at which two points can be distinguished as separate.", examiner_note: "Common error: confusing the two. Resolution requires 'distinguishable as separate'." },
  { id: "cb2", board: CIE, subject: "biology", topic: "Biological Molecules", question: "Describe the structure of DNA.", answer: "Double helix of two antiparallel polynucleotide strands; sugar-phosphate backbone; complementary base pairing (A-T with 2 H-bonds, C-G with 3); held together by hydrogen bonds.", examiner_note: "'Antiparallel' and the specific H-bond counts are commonly tested." },
  { id: "cb3", board: CIE, subject: "biology", topic: "Enzymes", question: "Explain the lock-and-key model of enzyme action.", answer: "The substrate has a complementary shape to the active site of the enzyme; only this specific substrate can bind to form an enzyme-substrate complex.", examiner_note: "'Complementary shape' (not 'same shape')." },
  { id: "cb4", board: CIE, subject: "biology", topic: "Cell Membranes", question: "Describe the fluid mosaic model of the cell membrane.", answer: "Phospholipid bilayer (hydrophilic heads outside, hydrophobic tails inside); proteins embedded (intrinsic) or attached (extrinsic); cholesterol regulates fluidity; carbohydrate chains for cell recognition.", examiner_note: "All four components for full marks." },
  { id: "cb5", board: CIE, subject: "biology", topic: "Mitotic Cell Cycle", question: "Describe the role of mitosis in living organisms.", answer: "Growth, repair (replacement of damaged cells), and asexual reproduction.", examiner_note: "Three uses for full marks; 'asexual reproduction' often forgotten." },
  { id: "cb6", board: CIE, subject: "biology", topic: "Transport in Mammals", question: "Describe the role of haemoglobin in oxygen transport.", answer: "Haemoglobin binds with oxygen in the lungs (high pO₂) to form oxyhaemoglobin; releases oxygen at respiring tissues (low pO₂); shows cooperative binding (sigmoidal dissociation curve).", examiner_note: "Reference both loading and unloading; mention partial pressure." },
  { id: "cb7", board: CIE, subject: "biology", topic: "Immunity", question: "Distinguish between active and passive immunity.", answer: "Active: own immune system produces antibodies after exposure to antigen (long-lasting). Passive: antibodies received from another source (mother or injection); short-lived; no memory cells.", examiner_note: "Compare in pairs; mention memory cells." },
  { id: "cb8", board: CIE, subject: "biology", topic: "Energy and Respiration", question: "Where does glycolysis occur and what is the net product?", answer: "In the cytoplasm; net products per glucose: 2 pyruvate, 2 ATP, 2 NADH (reduced NAD).", examiner_note: "'Net' — gross is 4 ATP minus 2 used = 2 ATP." },
  { id: "cb9", board: CIE, subject: "biology", topic: "Photosynthesis", question: "What happens during the light-dependent stage of photosynthesis?", answer: "Light absorbed by chlorophyll excites electrons; photolysis of water releases O₂; ATP and NADPH (reduced NADP) produced via the electron transport chain.", examiner_note: "Photolysis must be linked to oxygen production specifically." },
  { id: "cb10", board: CIE, subject: "biology", topic: "Inherited Change", question: "What is meant by codominance? Give an example.", answer: "Both alleles in a heterozygote are equally expressed in the phenotype. Example: ABO blood group AB shows both A and B antigens.", examiner_note: "Don't confuse with incomplete dominance (a blend, not both)." },

  // ===== CIE PHYSICS 9702 (10) =====
  { id: "cp1", board: CIE, subject: "physics", topic: "Physical Quantities and Units", question: "List the SI base units.", answer: "metre (m), kilogram (kg), second (s), ampere (A), kelvin (K), mole (mol), candela (cd).", examiner_note: "Candela rarely needed but expected for full marks in 'list all' questions." },
  { id: "cp2", board: CIE, subject: "physics", topic: "Kinematics", question: "Distinguish between scalar and vector quantities.", answer: "A scalar has magnitude only. A vector has both magnitude and direction.", examiner_note: "Examples (e.g. speed/velocity) often required." },
  { id: "cp3", board: CIE, subject: "physics", topic: "Forces", question: "State the principle of moments.", answer: "For a body in rotational equilibrium, the sum of clockwise moments about a point equals the sum of anticlockwise moments about the same point.", examiner_note: "'About the same point' is essential." },
  { id: "cp4", board: CIE, subject: "physics", topic: "Work Energy and Power", question: "Define power.", answer: "The rate of doing work, or rate of energy transfer: P = ΔW/Δt. Unit: watt (W) = J s⁻¹.", examiner_note: "Either definition (work or energy) accepted." },
  { id: "cp5", board: CIE, subject: "physics", topic: "Waves", question: "Define refraction.", answer: "The change in direction of a wave when it crosses a boundary between two media with different wave speeds.", examiner_note: "'Different wave speeds' is the cause — not 'different densities'." },
  { id: "cp6", board: CIE, subject: "physics", topic: "Superposition", question: "State the conditions for two waves to produce stable interference.", answer: "Same frequency, same wavelength, similar amplitude, and a constant phase difference (coherent sources).", examiner_note: "'Coherent' is the discriminating word — defined as constant phase difference." },
  { id: "cp7", board: CIE, subject: "physics", topic: "Particle Physics", question: "What are quarks?", answer: "Fundamental particles that combine to form hadrons. Up (u, +2/3), down (d, −1/3), and others. A proton is uud, a neutron is udd.", examiner_note: "Quark composition of proton and neutron expected." },
  { id: "cp8", board: CIE, subject: "physics", topic: "Capacitance", question: "Define capacitance.", answer: "The charge stored per unit potential difference across the capacitor: C = Q/V. Unit: farad (F) = C V⁻¹.", examiner_note: "'Per unit pd' (not 'per volt' alone)." },
  { id: "cp9", board: CIE, subject: "physics", topic: "Quantum Physics", question: "State the de Broglie relation.", answer: "λ = h/p, where λ is wavelength, h is Planck's constant, and p = mv is momentum.", examiner_note: "Define each symbol for full marks." },
  { id: "cp10", board: CIE, subject: "physics", topic: "Nuclear Physics", question: "What is meant by binding energy per nucleon?", answer: "The energy required to separate the nucleus into its individual nucleons, divided by the total number of nucleons.", examiner_note: "Per-nucleon basis is the key — peak is at iron-56." },

  // ===== CIE MATHS 9709 (10) =====
  { id: "cm1", board: CIE, subject: "mathematics", topic: "Quadratics", question: "How do you find the discriminant and what does it tell you?", answer: "For ax² + bx + c = 0, discriminant Δ = b² − 4ac. Δ > 0: two distinct real roots; Δ = 0: one repeated real root; Δ < 0: no real roots.", examiner_note: "All three cases must be stated for 3-mark questions." },
  { id: "cm2", board: CIE, subject: "mathematics", topic: "Functions", question: "State the conditions for a function to have an inverse.", answer: "The function must be one-to-one (injective) over its domain.", examiner_note: "'One-to-one' — not just 'invertible' (circular)." },
  { id: "cm3", board: CIE, subject: "mathematics", topic: "Coordinate Geometry", question: "State the equation of a circle with centre (a, b) and radius r.", answer: "(x − a)² + (y − b)² = r².", examiner_note: "Watch the sign: centre coordinates are subtracted." },
  { id: "cm4", board: CIE, subject: "mathematics", topic: "Circular Measure", question: "State the formulas for arc length and sector area in radians.", answer: "Arc length s = rθ. Sector area A = ½r²θ.", examiner_note: "θ must be in radians; common error to use degrees." },
  { id: "cm5", board: CIE, subject: "mathematics", topic: "Trigonometry", question: "State the Pythagorean trigonometric identity.", answer: "sin²x + cos²x = 1. Derived: 1 + tan²x = sec²x; 1 + cot²x = cosec²x.", examiner_note: "Know all three — derived identities tested in solving equations." },
  { id: "cm6", board: CIE, subject: "mathematics", topic: "Differentiation", question: "State the chain rule.", answer: "If y = f(g(x)), then dy/dx = f'(g(x)) · g'(x).", examiner_note: "Or: dy/dx = (dy/du)(du/dx) — both forms accepted." },
  { id: "cm7", board: CIE, subject: "mathematics", topic: "Integration", question: "State integration by parts.", answer: "∫u (dv/dx) dx = uv − ∫v (du/dx) dx.", examiner_note: "Choose u as the function whose derivative simplifies (LIATE: Log, Inverse, Algebraic, Trig, Exp)." },
  { id: "cm8", board: CIE, subject: "mathematics", topic: "Vectors", question: "How do you find the angle between two vectors?", answer: "Use the dot product: cos θ = (a · b) / (|a||b|).", examiner_note: "Always check the calculator is in the correct angle mode." },
  { id: "cm9", board: CIE, subject: "mathematics", topic: "Complex Numbers", question: "State De Moivre's theorem.", answer: "(cos θ + i sin θ)ⁿ = cos(nθ) + i sin(nθ) for any integer n.", examiner_note: "Used for finding powers and roots of complex numbers." },
  { id: "cm10", board: CIE, subject: "mathematics", topic: "Statistics", question: "State the central limit theorem.", answer: "For a sufficiently large sample size, the sampling distribution of the sample mean approximates a normal distribution, regardless of the population's distribution.", examiner_note: "'Sufficiently large' (n ≥ 30 typically) and 'regardless of population distribution' both important." },
];

export const TOPICS_BY_BOARD: Record<Board, string[]> = {
  "edexcel-ial": Array.from(new Set(EXAM_FAQS.filter(f => f.board === ED).map(f => f.topic))).sort(),
  "cie": Array.from(new Set(EXAM_FAQS.filter(f => f.board === CIE).map(f => f.topic))).sort(),
};
