// Hardcoded roadmap topic lists per the spec — Edexcel IAL fully supported.
// These supersede topic lists in src/lib/subjects.ts when generating the roadmap.

import type { SubjectCode } from "./subjects";

export const ROADMAP_TOPICS: Record<SubjectCode, Record<number, string[]>> = {
  chemistry: {
    1: [
      "Formulae, Equations and Amount of Substance",
      "Atomic Structure and the Periodic Table",
      "Bonding and Structure",
      "Introductory Organic Chemistry and Alkanes",
      "Alkenes",
    ],
    2: [
      "Energetics",
      "Intermolecular Forces",
      "Redox Chemistry and Groups 1, 2 and 7",
      "Introduction to Kinetics and Equilibria",
      "Halogenoalkanes, Alcohols and Spectra",
    ],
    3: [
      "Practical techniques (Units 1 & 2)",
      "Data analysis, uncertainties and evaluation",
      "Tests for ions, gases and organic functional groups",
    ],
    4: [
      "Kinetics",
      "Entropy and Energetics",
      "Chemical Equilibria",
      "Acid-base Equilibria",
      "Electrochemistry",
      "Transition Metals",
      "Reactions of Inorganic Compounds in Aqueous Solution",
    ],
    5: [
      "Arenes",
      "Aldehydes and Ketones",
      "Carboxylic Acids and Derivatives",
      "Nitrogen Compounds",
      "Polymerisation",
      "Chemical Analysis and Detection",
    ],
    6: [
      "Planning, Implementing and Safety",
      "Analysis and Evaluation",
      "Experimental Techniques",
    ],
  },

  biology: {
    1: [
      "Water Properties and Hydrogen Bonding",
      "Monosaccharides and Reducing Sugars",
      "Disaccharides and Glycosidic Bonds",
      "Polysaccharides — Glycogen and Starch",
      "Triglycerides and Fatty Acids",
      "Phospholipids and the Fluid Mosaic Model",
      "Cell Surface Membrane Structure",
      "Diffusion and Facilitated Diffusion",
      "Osmosis and Water Potential",
      "Active Transport",
      "DNA Structure",
      "RNA and the Genetic Code",
      "Transcription",
      "Translation",
      "Gene Mutations",
      "Genetic Screening — PCR and Gel Electrophoresis",
      "Why Animals Need a Circulatory System",
      "Blood Vessel Structure and Function",
      "Cardiac Cycle",
      "Heart Structure",
      "Haemoglobin and Oxygen Transport",
      "Atherosclerosis",
      "Blood Clotting",
      "Cardiovascular Disease Risk Factors",
    ],
    2: [
      "Prokaryotic Cell Structure",
      "Eukaryotic Cell Structure and Organelles",
      "Comparing Prokaryotic and Eukaryotic Cells",
      "Light Microscopy vs Electron Microscopy",
      "Cell Fractionation",
      "Cell Cycle and Mitosis",
      "Cancer and Uncontrolled Mitosis",
      "Meiosis and Genetic Variation",
      "Stem Cells and Totipotency",
      "Cell Differentiation",
      "β-glucose Structure",
      "Cellulose — Structure and Function",
      "Plant Cell Structure",
      "Classification — Three Domains and Five Kingdoms",
      "Phylogenetics and Molecular Evidence",
      "Biodiversity — Simpson's Diversity Index",
      "Sampling Methods — Quadrats and Transects",
      "Conservation — In Situ and Ex Situ",
    ],
    3: [
      "Enzyme Temperature Investigation",
      "Enzyme Substrate Concentration",
      "Enzyme pH Investigation",
      "Osmosis in Plant Tissue",
      "Microscopy and Cell Measurement",
      "Photosynthesis Rate — Light Wavelengths",
      "Transpiration and Potometers",
      "Statistical Analysis — t-test and Chi-squared",
      "Graph Skills and Error Bars",
      "Sources of Error — Systematic and Random",
      "Validity and Reliability in Biology Practicals",
    ],
    4: [
      "ATP Structure and Hydrolysis",
      "Light-Dependent Reactions of Photosynthesis",
      "Light-Independent Reactions — Calvin Cycle",
      "Limiting Factors for Photosynthesis",
      "Food Chains and Energy Flow in Ecosystems",
      "Gross and Net Primary Production",
      "Carbon Cycle",
      "Nitrogen Cycle and Eutrophication",
      "Bacterial Growth Phases",
      "Aseptic Technique and Culture Media",
      "Antibiotic Resistance",
      "Viruses — Influenza and Antigenic Variation",
      "Non-Specific Immunity and Phagocytosis",
      "Specific Humoral Immunity and B Cells",
      "Antibody Structure",
      "Specific Cell-Mediated Immunity and T Cells",
      "Primary and Secondary Immune Response",
      "Vaccines and Herd Immunity",
      "Monoclonal Antibodies",
      "HIV and AIDS",
    ],
    5: [
      "Glycolysis",
      "Link Reaction",
      "Krebs Cycle",
      "Oxidative Phosphorylation and Chemiosmosis",
      "Anaerobic Respiration",
      "Respiratory Quotient",
      "Homeostasis and Negative Feedback",
      "Thermoregulation",
      "Blood Glucose Regulation — Insulin and Glucagon",
      "Type 1 and Type 2 Diabetes",
      "Kidney Structure",
      "Ultrafiltration and Selective Reabsorption",
      "Loop of Henle — Countercurrent Multiplier",
      "ADH and Osmoregulation",
      "Neurone Structure",
      "Resting Potential",
      "Action Potential",
      "Saltatory Conduction",
      "Synaptic Transmission",
      "Endocrine Coordination",
      "PCR and Gel Electrophoresis",
      "Genetic Engineering and Recombinant DNA",
      "CRISPR-Cas9 Gene Editing",
      "Gene Therapy",
      "DNA Profiling",
    ],
    6: [
      "Antibiotic Effectiveness — Zones of Inhibition",
      "Microbial Growth Curves",
      "Investigating Photosynthesis with DCPIP",
      "Respiration with a Respirometer",
      "Fermentation Rate Investigation",
      "Chromatography of Chloroplast Pigments",
      "Advanced Statistical Tests — Mann-Whitney and Spearman's",
      "Evaluating Experimental Design",
      "Microbiological Counting Techniques",
    ],
  },

  physics: {
    1: [
      "Kinematics — SUVAT Equations",
      "Graphs of Motion",
      "Projectile Motion",
      "Free Fall and Terminal Velocity",
      "Newton's Laws of Motion",
      "Free Body Diagrams and Resolving Forces",
      "Moments, Couples and Equilibrium",
      "Work, Energy and Power",
      "Conservation of Energy",
      "Momentum and Impulse",
      "Elastic and Inelastic Collisions",
      "Density and Pressure",
      "Hooke's Law and Spring Constant",
      "Young's Modulus",
      "Stress-Strain Graphs and Material Properties",
    ],
    2: [
      "Wave Properties — Amplitude, Frequency, Wavelength",
      "Transverse and Longitudinal Waves",
      "Reflection and Refraction — Snell's Law",
      "Total Internal Reflection and Optical Fibres",
      "Diffraction and Superposition",
      "Stationary Waves — Nodes and Antinodes",
      "Interference and Young's Double Slit",
      "Diffraction Gratings",
      "Polarisation",
      "Electromagnetic Spectrum",
      "Photoelectric Effect",
      "Photons and Energy Levels",
      "De Broglie Wavelength and Wave-Particle Duality",
      "Electric Current, Charge and Drift Velocity",
      "Resistance, Resistivity and Ohm's Law",
      "I-V Characteristics",
      "Power and Energy in Circuits",
      "Series and Parallel Circuits",
      "EMF and Internal Resistance",
      "Kirchhoff's Laws",
      "Potential Dividers",
    ],
    3: [
      "Measurement Uncertainty and Error Analysis",
      "Significant Figures and Recording Results",
      "Types of Error — Random and Systematic",
      "Graph Skills — Best-Fit Lines and Gradients",
      "Linearising Relationships",
      "Free-Fall Experiment — Determining g",
      "Young's Modulus Experiment",
      "Spring Constant Experiment",
      "Newton's Second Law Verification",
      "Refractive Index of Glass",
      "I-V Characteristics Investigation",
      "Wavelength Measurement — Double Slit and Grating",
      "Resistivity Experiment",
      "EMF and Internal Resistance Experiment",
    ],
    4: [
      "Circular Motion",
      "Simple Harmonic Motion — Equations and Graphs",
      "Energy in Simple Harmonic Motion",
      "Damping and Resonance",
      "Newton's Law of Gravitation",
      "Gravitational Fields and Field Strength",
      "Gravitational Potential",
      "Orbital Mechanics and Kepler's Third Law",
      "Geostationary Orbits",
      "Coulomb's Law",
      "Electric Fields and Field Strength",
      "Electric Potential",
      "Capacitance",
      "Energy Stored in a Capacitor",
      "Capacitor Charging and Discharging",
      "Magnetic Force on Current and Charge",
      "Electromagnetic Induction and Faraday's Law",
      "Alternating Current",
      "Nuclear Atom and Radioactive Decay",
      "Binding Energy and Mass Defect",
      "Particle Physics — Quarks and the Standard Model",
    ],
    5: [
      "Thermal Energy Transfer",
      "Internal Energy and Temperature",
      "Ideal Gas Laws — Boyle's and Charles's Law",
      "Ideal Gas Equation",
      "Kinetic Theory of Gases",
      "Nuclear Radiation — Alpha, Beta, Gamma",
      "Half-Life and Radioactive Decay Equations",
      "Nuclear Fission and Fusion",
      "Astrophysics — Stellar Luminosity and Stefan's Law",
      "Hertzsprung-Russell Diagram",
      "Cosmology — Hubble's Law and the Big Bang",
    ],
    6: [
      "Advanced Uncertainty Analysis",
      "Evaluating Experimental Design in Physics",
      "SHM Experiments — Pendulum and Mass-Spring",
      "Investigating Capacitor Discharge",
      "Magnetic Field Investigations",
      "Radiation Safety and Measurements",
    ],
  },

  // Maths — units 1..8 = P1, P2, P3, P4, M1, M2, S1, S2.
  mathematics: {
    1: ["Algebra and Functions", "Coordinate Geometry", "Differentiation", "Integration", "Trigonometry", "Exponentials and Logarithms", "Vectors"],
    2: ["Further Algebra", "Further Coordinate Geometry", "Sequences and Series", "Further Trigonometry", "Further Calculus", "Numerical Methods"],
    3: ["Algebra and Functions (advanced)", "Further Trigonometry", "Differential Equations", "Further Vectors", "Complex Numbers"],
    4: ["Proof", "Further Algebra", "Polar Coordinates", "Hyperbolic Functions", "Further Differentiation and Integration", "Further Vectors"],
    5: ["Kinematics in One Dimension", "Kinematics in Two Dimensions", "Dynamics — Newton's Laws", "Statics and Equilibrium", "Moments"],
    6: ["Projectile Motion", "Rigid Bodies and Moments", "Elastic Strings and Springs", "Further Dynamics"],
    7: ["Representation and Summary of Data", "Probability", "Correlation and Regression", "Discrete Random Variables", "Normal Distribution"],
    8: ["Binomial Distribution", "Poisson Distribution", "Continuous Random Variables", "Hypothesis Testing"],
  },
};

const FOUNDATIONAL_KEYWORDS = [
  "algebra and functions",
  "proof",
  "atomic structure",
  "formulae, equations",
  "bonding and structure",
  "kinematics",
  "water properties",
  "monosaccharides",
  "prokaryotic cell",
  "kinematics in one dimension",
  "representation and summary",
  "mechanics",
  "wave properties",
];

export function isFoundationalTopic(topic: string): boolean {
  const t = topic.toLowerCase();
  return FOUNDATIONAL_KEYWORDS.some(k => t.includes(k));
}
