project_id = "womqjniplkfthbxkzlkb"

[functions.dodo-webhook]
verify_jwt = false

[functions.dodo-checkout]
verify_jwt = false

[functions.dodo-sync-subscription]
verify_jwt = false

[functions.dodo-cancel-subscription]
verify_jwt = false
