import { Link } from "react-router-dom";
import { ReactNode } from "react";
import { ApexLogo } from "@/components/ApexLogo";

const Shell = ({ title, children }: { title: string; children: ReactNode }) => (
  <div className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border/50 bg-background/85 backdrop-blur-xl sticky top-0 z-40">
      <div className="container flex h-14 items-center justify-between">
        <Link to="/" aria-label="Make Me Revise — home"><ApexLogo /></Link>
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground transition">← Back to home</Link>
      </div>
    </header>
    <main className="container max-w-3xl py-12 md:py-16">
      <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight mb-2">{title}</h1>
      <p className="text-xs font-mono uppercase tracking-wider text-muted-foreground mb-10">Effective date: May 2025</p>
      <div className="space-y-8 text-[15px] leading-relaxed text-foreground/90">{children}</div>
      <footer className="mt-16 pt-8 border-t border-border/50 flex flex-wrap gap-5 text-xs text-muted-foreground">
        <Link to="/terms" className="hover:text-foreground">Terms</Link>
        <Link to="/privacy" className="hover:text-foreground">Privacy</Link>
        <Link to="/refund" className="hover:text-foreground">Refunds</Link>
        <span className="ml-auto">© 2026 Make Me Revise</span>
      </footer>
    </main>
  </div>
);

const Section = ({ n, title, children }: { n: number; title: string; children: ReactNode }) => (
  <section>
    <h2 className="text-lg md:text-xl font-bold mb-2">{n}. {title}</h2>
    <div className="text-muted-foreground space-y-2">{children}</div>
  </section>
);

export const Terms = () => (
  <Shell title="Terms of Service">
    <Section n={1} title="What Make Me Revise is">
      <p>Make Me Revise is an AI-powered study platform built for A-Level students. We generate personalised revision roadmaps, practice questions, mock papers, and notes to help you prepare for your exams.</p>
    </Section>
    <Section n={2} title="Subscription terms">
      <p>Paid plans are billed monthly on a recurring basis. You can cancel anytime from your account settings — your access continues until the end of the current billing period.</p>
    </Section>
    <Section n={3} title="Free tier limitations">
      <p>The free plan includes the first 3 days of your roadmap, up to 10 AI-marked questions per day, and 1 mock paper per week. Upgrade to remove these limits.</p>
    </Section>
    <Section n={4} title="Pro tier">
      <p>Pro unlocks the full roadmap, unlimited questions, unlimited mock papers, unlimited notes, and the AI tutor. Pro is AED 39.99 per month, or the equivalent in your local currency.</p>
    </Section>
    <Section n={5} title="User responsibilities">
      <p>You must be at least 13 years old to use Make Me Revise. Accounts are personal — do not share your login with anyone else. Each account is for a single user.</p>
    </Section>
    <Section n={6} title="AI-generated content disclaimer">
      <p>All questions, notes, mark schemes, and feedback are generated by AI for revision guidance. While we work hard to keep content accurate and aligned to your syllabus, we do not guarantee exam accuracy. Always cross-check important facts with your teacher or official board materials.</p>
    </Section>
    <Section n={7} title="Intellectual property">
      <p>All content, branding, software, and AI-generated material on Make Me Revise belongs to Make Me Revise. You may use it for personal study but you may not republish, resell, or distribute it.</p>
    </Section>
    <Section n={8} title="Termination">
      <p>We may suspend or terminate accounts that abuse the platform — including sharing accounts, scraping content, attempting to break our systems, or violating these terms.</p>
    </Section>
    <Section n={9} title="Contact">
      <p>Questions about these terms? Email <a className="text-primary hover:underline" href="mailto:support@makemerevise.com">support@makemerevise.com</a>.</p>
    </Section>
  </Shell>
);

export const Privacy = () => (
  <Shell title="Privacy Policy">
    <Section n={1} title="What data we collect">
      <p>We collect your name, email address, study progress, exam dates, subject choices, and the answers you submit while practising.</p>
    </Section>
    <Section n={2} title="How we use it">
      <p>We use your data to personalise your roadmap and study plan, mark your work, track your progress, and improve the platform.</p>
    </Section>
    <Section n={3} title="We do not sell your data">
      <p>We do not sell, rent, or trade your personal data to any third party. Ever.</p>
    </Section>
    <Section n={4} title="Service providers">
      <p>We use Lovable Cloud to securely store your account and study data, and Dodo Payments to process payments. These providers only receive the data they need to deliver their service.</p>
    </Section>
    <Section n={5} title="Cookies">
      <p>We use essential cookies only — needed to keep you logged in and to remember your preferences. We do not use advertising or tracking cookies.</p>
    </Section>
    <Section n={6} title="Your rights">
      <p>You can request a copy or full deletion of your data at any time by emailing <a className="text-primary hover:underline" href="mailto:support@makemerevise.com">support@makemerevise.com</a>. We will action deletion requests within 30 days.</p>
    </Section>
    <Section n={7} title="Contact">
      <p>Privacy questions? Email <a className="text-primary hover:underline" href="mailto:support@makemerevise.com">support@makemerevise.com</a>.</p>
    </Section>
  </Shell>
);

export const Refund = () => (
  <Shell title="Refund Policy">
    <Section n={1} title="7-day money-back guarantee">
      <p>If you are not satisfied within 7 days of your first payment, email us for a full refund — no questions asked.</p>
    </Section>
    <Section n={2} title="After 7 days">
      <p>We do not refund the current billing period after the 7-day window. You can cancel anytime from your account settings and you will not be charged again.</p>
    </Section>
    <Section n={3} title="How to request a refund">
      <p>Email <a className="text-primary hover:underline" href="mailto:support@makemerevise.com">support@makemerevise.com</a> with the subject line <span className="font-mono text-foreground">"Refund Request"</span>. Include the email address on your account so we can find your payment.</p>
    </Section>
    <Section n={4} title="Processing time">
      <p>Approved refunds are processed within 5–10 business days. The funds may take a few additional days to appear depending on your bank or card provider.</p>
    </Section>
  </Shell>
);
