import { Link } from "react-router-dom";
import { ReactNode } from "react";
import { SEO } from "@/components/SEO";

const SIA_LOGO = "/sia-logo.png";
const SUPPORT_EMAIL = "admissions@sia.ae";

const Shell = ({ title, description, path, children }: { title: string; description: string; path: string; children: ReactNode }) => (
  <div className="min-h-screen bg-background text-foreground">
    <SEO title={`${title} — SIA Smart Revision`} description={description} path={path} />
    <header className="border-b border-border/50 bg-background/85 backdrop-blur-xl sticky top-0 z-40">
      <div className="container flex h-14 items-center justify-between">
        <Link to="/" aria-label="SIA Smart Revision — home" className="flex items-center gap-2">
          <img src={SIA_LOGO} alt="SIA" className="h-8 w-8 rounded-full object-contain" />
          <span className="font-bold text-sm" style={{ fontFamily: "'Playfair Display',Georgia,serif", color: "hsl(var(--primary))" }}>SIA Smart Revision</span>
        </Link>
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground transition">← Back to home</Link>
      </div>
    </header>
    <main className="container max-w-3xl py-12 md:py-16">
      <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight mb-2">{title}</h1>
      <p className="text-xs font-mono uppercase tracking-wider text-muted-foreground mb-10">Effective date: June 2026 · Scholars International Academy, Sharjah, UAE</p>
      <div className="space-y-8 text-[15px] leading-relaxed text-foreground/90">{children}</div>
      <footer className="mt-16 pt-8 border-t border-border/50 flex flex-wrap gap-5 text-xs text-muted-foreground">
        <Link to="/terms" className="hover:text-foreground">Terms</Link>
        <Link to="/privacy" className="hover:text-foreground">Privacy</Link>
        <span className="ml-auto">© {new Date().getFullYear()} Scholars International Academy</span>
      </footer>
    </main>
  </div>
);

const Section = ({ n, title, children }: { n: number; title: string; children: ReactNode }) => (
  <section>
    <h2 className="text-lg md:text-xl font-bold mb-2">{n}. {title}</h2>
    <div className="text-muted-foreground space-y-2">{children}</div>
  </section>
);

export const Terms = () => (
  <Shell title="Terms of Service" path="/terms" description="The terms that govern use of SIA Smart Revision — the official AI revision platform of Scholars International Academy.">
    <Section n={1} title="About SIA Smart Revision">
      <p>SIA Smart Revision is the official AI-powered revision platform provided by Scholars International Academy ("SIA", "the school", "we") for its students, parents, and teaching staff. It offers personalised revision roadmaps, AI-generated notes, practice questions, and mock papers to support exam preparation.</p>
    </Section>
    <Section n={2} title="Who can use it">
      <p>The platform is provided for the SIA community: currently enrolled SIA students, their parents or guardians, and SIA staff. Accounts are personal to each user and must not be shared. The school may issue, suspend, or remove accounts at its discretion.</p>
    </Section>
    <Section n={3} title="No charge">
      <p>SIA Smart Revision is provided to the SIA community free of charge as part of the school's educational services. There are no subscriptions, fees, or payments associated with using the platform.</p>
    </Section>
    <Section n={4} title="Acceptable use">
      <p>You agree to use the platform only for legitimate study and educational purposes. You must not share your login, attempt to access other users' data, scrape or copy content in bulk, or interfere with the platform's operation.</p>
    </Section>
    <Section n={5} title="Roles and visibility">
      <p>The platform supports student, parent, and teacher roles. A student's study activity and progress may be visible to their linked parent(s)/guardian(s) and to SIA teaching staff, for the purpose of supporting the student's learning.</p>
    </Section>
    <Section n={6} title="AI-generated content disclaimer">
      <p>Questions, notes, mark schemes, and feedback are generated by AI for revision guidance. While we work to keep content accurate and aligned to the relevant syllabus, accuracy is not guaranteed. Always cross-check important facts with your teacher and official exam-board materials.</p>
    </Section>
    <Section n={7} title="Intellectual property">
      <p>The platform, its branding, and its content are provided for the personal study of the SIA community. You may not republish, resell, or distribute the content outside the school.</p>
    </Section>
    <Section n={8} title="Availability">
      <p>The platform is provided "as is". The school may update, change, or withdraw features at any time, and does not guarantee uninterrupted availability.</p>
    </Section>
    <Section n={9} title="Termination">
      <p>The school may suspend or remove access for accounts that misuse the platform or breach these terms.</p>
    </Section>
    <Section n={10} title="Contact">
      <p>Questions about these terms? Email <a className="text-primary hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
    </Section>
  </Shell>
);

export const Privacy = () => (
  <Shell title="Privacy Policy" path="/privacy" description="How SIA Smart Revision collects, uses, and protects student, parent, and teacher data. We never sell personal information.">
    <Section n={1} title="Who controls your data">
      <p>Scholars International Academy is the data controller for SIA Smart Revision. This policy explains what we collect and how it is used within the platform.</p>
    </Section>
    <Section n={2} title="What we collect">
      <p>We collect your name, email address, role (student / parent / teacher), and — for students — Student ID, year group and section. We also record study activity such as time studied, roadmap progress, questions attempted, mock-paper scores, and login activity.</p>
    </Section>
    <Section n={3} title="How we use it">
      <p>We use this data to personalise revision, mark work, track progress, and show that progress to the student, their linked parent(s)/guardian(s), and SIA teaching staff so they can support the student's learning.</p>
    </Section>
    <Section n={4} title="Who can see student data">
      <p>A student's data is visible to: the student themselves, parent(s)/guardian(s) who have linked to that student using the Student ID, and SIA teaching staff. It is not visible to other students or to anyone outside the school.</p>
    </Section>
    <Section n={5} title="We do not sell your data">
      <p>We do not sell, rent, or trade personal data to any third party. Ever.</p>
    </Section>
    <Section n={6} title="Service providers">
      <p>We use trusted providers strictly to operate the platform: Supabase (secure cloud storage and authentication), Google (optional "Sign in with Google"), and AI providers such as Google Gemini to generate study content. They receive only the data needed to deliver their service.</p>
    </Section>
    <Section n={7} title="Cookies">
      <p>We use essential cookies only — needed to keep you signed in and remember your preferences. We do not use advertising or third-party tracking cookies.</p>
    </Section>
    <Section n={8} title="Children's data">
      <p>The platform is used by school students under the care of SIA. The school acts as the data controller and handles student data in line with its safeguarding and data-protection responsibilities.</p>
    </Section>
    <Section n={9} title="Your rights">
      <p>You can request a copy or deletion of your data by emailing <a className="text-primary hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Requests are actioned in line with the school's data-protection process.</p>
    </Section>
    <Section n={10} title="Contact">
      <p>Privacy questions? Email <a className="text-primary hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
    </Section>
  </Shell>
);

// Retained for the /refund route — the platform is free, so this simply explains that.
export const Refund = () => (
  <Shell title="No Payments" path="/refund" description="SIA Smart Revision is provided free of charge by Scholars International Academy.">
    <Section n={1} title="Provided free of charge">
      <p>SIA Smart Revision is provided to the SIA community free of charge as part of the school's educational services. There are no subscriptions, fees, payments, or refunds associated with the platform.</p>
    </Section>
    <Section n={2} title="Questions">
      <p>For any questions, email <a className="text-primary hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
    </Section>
  </Shell>
);
