import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from "@/contexts/AuthContext";
import { MaintenanceGate } from "@/components/MaintenanceGate";
import Landing from "./pages/Landing";
import AuthPage from "./pages/Auth";
import Diagnostic from "./pages/Diagnostic";
import Onboarding from "./pages/Onboarding";
import Dashboard from "./pages/Dashboard";
import Questions from "./pages/Questions";
import MockPapers from "./pages/MockPapers";
import NewMockPaper from "./pages/NewMockPaper";
import MockExam from "./pages/MockExam";
import MockResults from "./pages/MockResults";
import Roadmap from "./pages/Roadmap";
import RoadmapTopicNotes from "./pages/RoadmapTopicNotes";
import { StubPage } from "./components/StubPage";
import { RequirePro } from "./components/RequirePro";
import Notes from "./pages/Notes";
import Podcast from "./pages/Podcast";
import PastPapers from "./pages/PastPapers";
import FAQ from "./pages/FAQ";
import Settings from "./pages/Settings";
import Exams from "./pages/Exams";
import Pricing from "./pages/Pricing";
import Feedback from "./pages/Feedback";
import NotFound from "./pages/NotFound";
import { Terms, Privacy, Refund } from "./pages/Legal";
import { ClarityCompassHome } from "./pages/ClarityCompass/ClarityCompassHome";\nimport { ClarityOnboarding } from "./pages/ClarityCompass/ClarityOnboarding";\nimport { ClarityQuiz } from "./pages/ClarityCompass/ClarityQuiz";\nimport { ClarityResults } from "./pages/ClarityCompass/ClarityResults";\nimport { ClarityRoadmap } from "./pages/ClarityCompass/ClarityRoadmap";\nimport { ClarityProfile } from "./pages/ClarityCompass/ClarityProfile\";\n\nconst queryClient = new QueryClient();\n\nconst App = () => (\n  <QueryClientProvider client={queryClient}>\n    <AuthProvider>\n      <TooltipProvider>\n        <Toaster />\n        <Sonner />\n        <BrowserRouter>\n          <MaintenanceGate>\n          <Routes>\n            <Route path=\"/\" element={<Landing />} />\n            <Route path=\"/auth\" element={<AuthPage />} />\n            <Route path=\"/diagnostic\" element={<Diagnostic />} />\n            <Route path=\"/onboarding\" element={<Onboarding />} />\n            <Route path=\"/dashboard\" element={<Dashboard />} />\n            <Route path=\"/questions\" element={<Questions />} />\n            <Route path=\"/mock-papers\" element={<MockPapers />} />\n            <Route path=\"/mock-papers/new\" element={<NewMockPaper />} />\n            <Route path=\"/mock-papers/exam/:id\" element={<MockExam />} />\n            <Route path=\"/mock-papers/:id/results\" element={<MockResults />} />\n            <Route path=\"/roadmap\" element={<Roadmap />} />\n            <Route path=\"/roadmap/topic/:nodeId/notes\" element={<RoadmapTopicNotes />} />\n            <Route path=\"/notes\" element={<Notes />} />\n            <Route path=\"/podcast\" element={<Podcast />} />\n            <Route path=\"/papers\" element={<PastPapers />} />\n            <Route path=\"/faq\" element={<RequirePro featureName=\"Exam FAQs\"><FAQ /></RequirePro>} />\n            <Route path=\"/settings\" element={<Settings />} />\n            <Route path=\"/exams\" element={<Exams />} />\n            <Route path=\"/pricing\" element={<Pricing />} />\n            <Route path=\"/feedback\" element={<Feedback />} />\n            <Route path=\"/terms\" element={<Terms />} />\n            <Route path=\"/privacy\" element={<Privacy />} />\n            <Route path=\"/refund\" element={<Refund />} />\n            <Route path=\"/clarity-compass\" element={<ClarityCompassHome />} />\n            <Route path=\"/clarity-compass/onboarding\" element={<ClarityOnboarding />} />\n            <Route path=\"/clarity-compass/quiz\" element={<ClarityQuiz />} />\n            <Route path=\"/clarity-compass/results\" element={<ClarityResults />} />\n            <Route path=\"/clarity-compass/roadmap\" element={<ClarityRoadmap />} />\n            <Route path=\"/clarity-compass/profile\" element={<ClarityProfile />} />\n            <Route path=\"*\" element={<NotFound />} />\n          </Routes>\n          </MaintenanceGate>\n        </BrowserRouter>\n      </TooltipProvider>\n    </AuthProvider>\n  </QueryClientProvider>\n);\n\nexport default App;\n